import Head from 'next/head'

import Project from "../../components/project"

export default function Main() {
  return (
    <>
      <Head>
        <title>Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Project />
    </>
  )
}